services:
  nginx:
    container_name: nginx
    ports:
      - "2024:80"
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
      - booksearcher-crawler
    restart: always
    environment:
      - TZ=Asia/Seoul

  booksearcher-crawler:
    container_name: booksearcher-crawler
    ports:
      - "8000:8000"
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - booksearcher-crawler:/app/util/log/logfile

volumes:
  booksearcher-crawler: